function params = init_parameters()
% init_parameters - 初始化所有仿真参数
%
% 输出:
%   params: 参数结构体，包含仿真域、智能体、羽流、密度、算法和仿真参数

    %% === 场景参数 ===
    params.domain = struct( ...
        'xmin', 30,   'xmax', 390, ...
        'ymin', -160, 'ymax', 160, ...
        'zmin', -260, 'zmax', 0);

    %% === 智能体参数 ===
    params.agent = struct( ...
        'num', 8, ...
        'max_speed', 3.5, ...
        'control_gain', 0.28, ...
        'sense_radius', 50);

    %% === 溢油羽流参数 ===
    params.plume = struct( ...
        'source_pos', [150, 0, -180], ...
        'Q', 100, ...
        'u_current', 0.5, ...
        'w_buoyancy', 0.22, ...
        'sigma_x0', 28, ...
        'sigma_y0', 16, ...
        'sigma_z0', 14, ...
        'diffusion_x', 1.20, ...
        'diffusion_y', 2.60, ...
        'diffusion_z', 1.10, ...
        'decay_rate', 0.0006, ...
        'release_substeps', 28, ...
        'front_smoothing', 45, ...
        'boundary_threshold', 0.035);

    %% === 密度函数参数 ===
    params.density = struct( ...
        'alpha', 10.0, ...
        'beta', 0.03);

    %% === 算法参数 ===
    params.algorithm = struct( ...
        'sample_num', 50000, ...
        'dt', 1.0, ...
        'ff_gain', 0.12, ...
        'boundary_gain', 1.10, ...
        'boundary_sample_num', 12000);

    %% === 仿真参数 ===
    params.sim = struct( ...
        'total_time', 200, ...
        'pre_release_time', 80, ...
        'plume_update_interval', 5, ...
        'sample_num_test', 5000);

    %% === 预计算最大浓度（用于归一化和边界阈值） ===
    src = params.plume.source_pos;
    sample_times = linspace(1, params.sim.total_time * params.algorithm.dt, 12);
    C_max_samples = zeros(size(sample_times));
    for i = 1:numel(sample_times)
        center_x = src(1) + params.plume.u_current * sample_times(i) * 0.35;
        center_z = min(0, src(3) + params.plume.w_buoyancy * sample_times(i) * 0.35);
        C_max_samples(i) = gaussian_plume_3d(center_x, src(2), center_z, sample_times(i), params);
    end
    params.plume.C_max_estimate = max(max(C_max_samples) * 1.2, eps);
end
