function params = init_parameters()
% init_parameters - 初始化所有仿真参数
%
% 输出:
%   params: 参数结构体，包含仿真域、智能体、羽流、密度、算法和仿真参数

    %% === 场景参数 ===
    params.domain = struct( ...
        'xmin', 0,    'xmax', 500, ...
        'ymin', -200, 'ymax', 200, ...
        'zmin', -300, 'zmax', 0);

    %% === 智能体参数 ===
    params.agent = struct( ...
        'num', 8, ...
        'max_speed', 2.0, ...
        'control_gain', 0.45, ...
        'sense_radius', 90);

    %% === 溢油羽流参数 ===
    params.plume = struct( ...
        'source_pos', [50, 0, -50], ...
        'Q', 100, ...
        'u_current', 0.5, ...
        'sigma_x0', 35, ...
        'sigma_y0', 15, ...
        'sigma_z0', 10, ...
        'kx', 0.16, ...
        'ky', 0.22, ...
        'kz', 0.12, ...
        'diffusion_x', 1.40, ...
        'diffusion_y', 2.80, ...
        'diffusion_z', 0.90, ...
        'decay_rate', 0.0006, ...
        'front_initial_extent', 210, ...
        'front_smoothing', 55, ...
        'boundary_threshold', 0.035);

    %% === 密度函数参数 ===
    params.density = struct( ...
        'alpha', 10.0, ...
        'beta', 0.03);

    %% === 算法参数 ===
    params.algorithm = struct( ...
        'sample_num', 50000, ...
        'dt', 1.0, ...
        'ff_gain', 0.25, ...
        'boundary_gain', 0.35, ...
        'boundary_sample_num', 12000);

    %% === 仿真参数 ===
    params.sim = struct( ...
        'total_time', 200, ...
        'plume_update_interval', 5, ...
        'sample_num_test', 5000);

    %% === 预计算最大浓度（用于归一化和边界阈值） ===
    src = params.plume.source_pos;
    C_test = gaussian_plume_3d(src(1) + 10, src(2), src(3), 1, params);
    params.plume.C_max_estimate = max(C_test * 1.2, eps);
end
